FROM node:carbon

# Create app directory
WORKDIR /srv

ENV SOURCE_ENV dist
ENV NODE_ENV=production

COPY package*.json ./
RUN npm install pm2 -g
RUN npm install --only=production

# Bundle app source
COPY . .
RUN npm run build

EXPOSE 3000
CMD [ "pm2-runtime", "app.js" ]