FROM node:carbon

EXPOSE 4000
EXPOSE 5000
EXPOSE 1234
EXPOSE 80

# Create app directory
WORKDIR /srv

ENV NODE_ENV=production
ENV PORT=5000

COPY package*.json ./
#RUN npm install
RUN npm install pushstate-server

# Bundle app source
COPY . .
#RUN rm -rf dist
#RUN mkdir dist
#RUN npm run build

CMD [ "node", "./tools/server.js" ]